name: maven
description: Powerful cross-platform workout app that helps you track your progress and reach your fitness goals.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  # Development
  intl_utils: ^2.8.3
  build_runner: ^2.3.3
  sqlite_viewer: ^1.0.5
  # Database
  sqflite: ^2.2.2
  floor: ^1.4.1
  floor_generator: ^1.4.1
  # State Management
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  # User Interface
  cupertino_icons: ^1.0.5
  expandable: ^5.0.1
  sliding_up_panel: ^2.0.0+1
  flutter_colorpicker: ^1.0.3
  timeago: ^3.3.0
  reorderables: ^0.6.0
  shimmer: ^3.0.0
  flutter_slidable: ^3.0.0
  video_player: ^2.6.1
  reorderable_grid: ^1.0.6
  flutter_markdown: ^0.6.15+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: false
  assets:
    - assets/images/
    - assets/exercises/videos/

flutter_intl:
  enabled: true